### ISSUE TITLE
App crash on takePhoto call (iOS)

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-plugin-image-capture#26]
### Expected Behaviour
Expect takePhoto to take a photo
### Actual Behaviour
It crash
#### Steps to Reproduce

Create a Cordova project and use the code on sample code (below)
Click the white camera button.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
iOS 10 and iOS 11 iPads

#### Cordova CLI version and cordova platform version

    cordova --version                                7.1.0
    cordova platform version ios              4.5.3

#### Plugin version

    cordova plugin version | grep phonegap-plugin-image-capture   1.1.2

#### Sample Code that illustrates the problem
```
navigator.mediaDevices.getUserMedia({
            'audio': true,
            'video': {
                facingMode: 'user'
            }
        }).then(function(getmedia) {
            var track = getmedia.getVideoTracks()[0];
            var imageCapture = new ImageCapture(track);
            imageCapture.takePhoto()
            .then(blob => {
                console.log('Photo taken: ' + blob.type + ', ' + blob.size + 'B');
                const image = document.querySelector('img'); // img is an <img> tag
                image.src = URL.createObjectURL(blob);
            })
            .catch(err => console.error('takePhoto() failed: ', err));
        });
```

#### Logs taken while reproducing problem

-[CDVImageCapture sendPluginResult:keepResult:]: unrecognized selector sent to instance 0x1c80d5930
2017-11-13 20:05:58.340979+0100 wkgeo[436:88432] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CDVImageCapture sendPluginResult:keepResult:]: unrecognized selector sent to instance 0x1c80d5930'

**Comment by macdonst** [comment]
@jcesarmobile thanks for finding the bug and sending a PR.

**Comment by jcesarmobile** [comment]
NP, always happy to help

**Comment by gloaguen** [comment]
I still have this problem, tested this with IOS 11.2

**Comment by jcesarmobile** [comment]
I don't think it has been released, so install from github url instead of installing from npm

**Comment by gloaguen** [comment]
@jcesarmobile I already tried the github url, but the iOS app still crashes after clicking the "takePicture" icon, the video stream is showing correctly.

**Comment by jcesarmobile** [comment]
Then create a new issue and provide more information
